title:        API Evangelist API Provider 101
description: This is an overview of the world of APIs, providing a 101 level walk through of APIs from the provider perspective.
url: http://101.provider.apievangelist.com
raw_url: twitter.lesson.apievangelist.com/apis/

tag: 101

logo:         https://s3.amazonaws.com/kinlane-productions2/api-evangelist/api-evangelist-logo-lessons.png
logo_width:   80
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 25
paginate_path: "/blog/page:num"

github_user: api-evangelist-api-consumer-lessons
github_repo: 101-provider
github_branch: master

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions2/footer/empowered-by-you-banner.png
footer_image_width: 60
